services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   
      MYSQL_DATABASE: mydatabase        
      MYSQL_USER: meuuser                 
      MYSQL_PASSWORD: minhasenha          
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql                    
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    ports:
      - "8080:80"                       
    restart: unless-stopped
    networks:
      - db_network

volumes:
  mysql_data:

networks:
  db_network:
    driver: bridge